admin: hype연어 # 실험자 이름
patience: 5
seed: 42
train:
  model: klue/bert-base
  batch_size: 128
  epoch: 1
  LR: 0.00001
  LossF: CrossEntropyLoss
  optim: AdamW
  shuffle: True
  max_len: 50
  scheduler: None
inference:
  model: klue/bert-base
  batch_size: 128
EarlyStopping:
  turn_on: True # False
  monitor: valid_f1_score # valid_acc_score / valid_loss
  min_delta: 0.00
  patience: 3
  verbose: True 

