admin: hype연어 # 실험자 이름
patience: 5
seed: 42
model:
  model_name: klue/roberta-large
  batch_size: 16
  epoch: 5
  LR: 0.00001
  LossF: CrossEntropyLoss
  optim: AdamW
  shuffle: True
  max_len: 50
  scheduler: None
EarlyStopping:
  turn_on: True # False
  monitor: valid_f1_score # valid_acc_score / valid_loss
  min_delta: 0.00
  patience: 3
  verbose: True 
data_processing:
  random_insertion: True
  random_swap: True
  sub_ob_swap: True
  same_type_swap: True
