admin: KYH # 실험자 이름
patience: 5
seed: 42
train:
  model: klue/roberta-large
  batch_size: 32
  epoch: 10
  LR: 0.00001
  LossF: CrossEntropyLoss
  optim: AdamW
  shuffle: True
  max_len: 50
  scheduler: None
inference:
  model: klue/roberta-large
  batch_size: 32